spring:
  application:
    name: SSLFlux
sslflux:
  cloud:
    aliyun:
      access-key: AK_xxxx
      secret-key: SK_yyyy
acme:
#  serverUri: https://acme-staging-v02.api.letsencrypt.org/directory
  serverUri: https://acme-v02.api.letsencrypt.org/directory