spring:
  application:
    name: SSLFlux
sslflux:
  cloud:
    aliyun:
      access-key: xxx
      secret-key: xxx

acme:
#  serverUri: https://acme-v02.api.letsencrypt.org/directory
  serverUri: https://dv.acme-v02.api.pki.goog/directory
  kid: xx
  macKey: xxx
  keystore:
    # Windows路径格式
    file: file:D:/sslcret/keystore.p12
    # Linux/macOS格式
    # file: file:/home/user/sslcret/keystore.p12
    password: mySecurePassword123
  contact:
    email: 1234567@qq.com

